### PR TITLE
Whitespace is not trimmed from the end of query strings

### LINKED ISSUE #1260: [Bug Report] Whitespace is not trimmed from the end of query strings
**Describe the bug**
If any whitespace characters follow the final character of a query, the entire Stash DB is returned as a result.

**To Reproduce**
1. Given that "MacAndCheese" is the name of a file, enter a query of "MacAndCheese " 
2. Observe that the entirety of the Stash DB is returned from the query rather than just "MacAndCheese"

**Expected behavior**
1. Given that "MacAndCheese" is the name of a file, enter a query of "MacAndCheese " 
2. Stash should return a result as if "MacAndCheese" has been entered, regardless of how much whitespace is entered at the end.

**Desktop (please complete the following information):**
 - OS: Windows 10 20H2
 - Browser: Google Chrome 89.x
 - Stash Version: v0.6.0

### PR DESCRIPTION
**Pull request by julien0221**
I added a trim on the query strings so now it doesn't returns all the search if there are one or more space at the end of query.
Resolves #1260

### CODE REVIEW

**Comment by InfiniteTF** [comment]
We should trim the query string on the backend as well so any scripts/external apps don't run into the same issue. Also, filtering out zero length clauses, which is presumably what happens when there are multiple sequential spaces in the middle of the query.

**Comment by julien0221** [comment]
sure, I added a fix to trim it on backend too

File: pkg/sqlite/sql.go [hunk 1]
```diff
@@ -108,7 +108,8 @@ func getSearchBinding(columns []string, q string, not bool) (string, []interface
 	}
 
 	queryWords := strings.Split(q, " ")
-	trimmedQuery := strings.Trim(q, "\"")
+	trimmedQuery := strings.Trim(q, " \"")
```
Comment (WithoutPants) [inline pkg/sqlite/sql.go:111]: This will result in inconsistent behaviour:

Search `aaa bbb`, searches `aaa` or `bbb`.
Search ` aaa bbb` (leading whitespace), will search `aaa bbb` because `trimmedQuery != q`.

If we're improving this code, then we should address another issue:
Search `aaa  bbb` (double-space), will return everything, due to one of the `queryWords` being `""`.

Suggest the following:
* trim whitespace first
* if string starts and ends with `"`, then search exact query
* otherwise, split using `" "`, remove any empty strings, and search for any of the words

This also needs to have unit tests added.

**Review by WithoutPants — CHANGES_REQUESTED** [review]

File: pkg/sqlite/sql.go (hunk 1 above)
Comment (julien0221) [reply pkg/sqlite/sql.go]: ok I changed the way to deal with double space and whitespace. And I added unit tests.

File: pkg/sqlite/sql.go [hunk 2]
```diff
@@ -106,9 +107,11 @@ func getSearchBinding(columns []string, q string, not bool) (string, []interface
 		notStr = " NOT"
 		binaryType = " AND "
 	}
-
+	q = strings.TrimSpace(q)
+	q = regexp.MustCompile(`\s+`).ReplaceAllString(q, " ")
 	queryWords := strings.Split(q, " ")
 	trimmedQuery := strings.Trim(q, "\"")
+
 	if trimmedQuery == q {
```
Comment (bnkai) [inline pkg/sqlite/sql.go:115]: If we relax a bit on the "exact" query this is ok.
If "exact" though includes spaces then this is not ok and test `q = "   \"Girl     does   threesome\" "` (multiple spaces in the quoted query vs single in the title) should fail
If the later is what we want then the 
```golang
q = regexp.MustCompile(`\s+`).ReplaceAllString(q, " ")
queryWords := strings.Split(q, " ")
```
should be moved inside the 
```golang
if trimmedQuery == q {
```

File: pkg/sqlite/scene_test.go [hunk 3]
```diff
@@ -1376,6 +1376,60 @@ func TestSceneStashIDs(t *testing.T) {
...
+			Q: &q,
+		}
+
+		scenes = queryScene(t, qb, nil, &findFilter)
+		assert.Len(t, scenes, 1)
+		assert.Equal(t, scenes[0].ID, created.ID)
+
+		findFilter.Q = nil
+		scenes = queryScene(t, qb, nil, &findFilter)
+		assert.NotEqual(t, 0, len(scenes))
```
Comment (bnkai) [inline pkg/sqlite/scene_test.go:1425]: rewritting the test a bit makes it easier to add some more queries imho
```golang
                type test struct {
                        query string
                        id    int
                        count int
                }
                tests := []test{
                        {query: " Girl    does    ", id: created.ID, count: 1},
                        {query: "   \"Girl     does   threesome\" ", id: created.ID, count: 1},
                        {query: "threesome", id: created.ID, count: 1},
                }

                for _, tst := range tests {
                        f := models.FindFilterType{
                                Q: &tst.query,
                        }
                        scenes := queryScene(t, qb, nil, &f)

                        assert.Len(t, scenes, tst.count)
                        assert.Equal(t, tst.id, scenes[0].ID)
                }

                findFilter := models.FindFilterType{}
                scenes := queryScene(t, qb, nil, &findFilter)
                assert.NotEqual(t, 0, len(scenes))
```

File: pkg/sqlite/sql.go (hunk 2 above)
Comment (julien0221) [reply pkg/sqlite/sql.go:115]: You are right, exact should be exactly what the user want to type.

File: pkg/sqlite/scene_test.go (hunk 3 above)
Comment (julien0221) [reply pkg/sqlite/scene_test.go]: Awesome, thank you for the change, I am still new with Golang :)

**Review by WithoutPants — APPROVED** [review]
