### PR TITLE
Preview generation fallback

### LINKED ISSUE #635: cannot generate .wmv sprites and markers
it seems that .wmv files are not being sprites and markers are not being generated due to an error in ffmpeg

**To Reproduce**
1. use docker container on windows with latest:development version
2. place .wmv files in your data directory
3. scan library
4. check sprites and markers and click generate in the stash settings

**Expected behavior**
no errors. and sprite and marker generation for .wmv files

**Stash Version: (from Settings -> About):**
883a0e7

**Desktop (please complete the following information):**
 - OS: windows
 - Browser: firefox
 - Version: latest

**Additional context**
Error log:
```stash_1 | time="2020-06-25T19:29:03Z" level=info msg="[generator] generating scene preview for /data/sites/video.wmv"

stash_1 | time="2020-06-25T19:29:03Z" level=error msg="ffmpeg error when running command </usr/bin/ffmpeg -v error -xerror -ss 0 -i /data/sites/video.wmv -t 0.75 -max_muxing_queue_size 1024 -y -c:v libx264 -pix_fmt yuv420p -profile:v high -level 4.2 -preset slow -crf 21 -threads 4 -vf scale=640:-2 -c:a aac -b:a 128k -strict -2 /generated/tmp/preview000.mp4>: [mp4 @ 0x5555565536c0] Non-monotonous DTS in output stream 0:1; previous: 15360, current: 13362; aborting.\n"

stash_1 | time="2020-06-25T19:29:03Z" level=error msg="ffmpeg error when running command </usr/bin/ffmpeg -v error -xerror -ss 266 -i /data/sites/video.wmv -t 0.75 -max_muxing_queue_size 1024 -y -c:v libx264 -pix_fmt yuv420p -profile:v high -level 4.2 -preset slow -crf 21 -threads 4 -vf scale=640:-2 -c:a aac -b:a 128k -strict -2 /generated/tmp/preview001.mp4>: /data/sites/video.wmv: corrupt decoded frame in stream 1\n"

stash_1 | time="2020-06-25T19:29:03Z" level=error msg="ffmpeg error when running command </usr/bin/ffmpeg -v error -xerror -ss 532 -i /data/sites/video.wmv -t 0.75 -max_muxing_queue_size 1024 -y -c:v libx264 -pix_fmt yuv420p -profile:v high -level 4.2 -preset slow -crf 21 -threads 4 -vf scale=640:-2 -c:a aac -b:a 128k -strict -2 /generated/tmp/preview002.mp4>: /data/sites/video.wmv: corrupt decoded frame in stream 1\n"

stash_1 | time="2020-06-25T19:29:05Z" level=error msg="ffmpeg error when running command </usr/bin/ffmpeg -v error -xerror -ss 1596 -i /data/sites/video.wmv -t 0.75 -max_muxing_queue_size 1024 -y -c:v libx264 -pix_fmt yuv420p -profile:v high -level 4.2 -preset slow -crf 21 -threads 4 -vf scale=640:-2 -c:a aac -b:a 128k -strict -2 /generated/tmp/preview006.mp4>: /data/sites/video.wmv: corrupt decoded frame in stream 1\n"

stash_1 | time="2020-06-25T19:29:05Z" level=error msg="ffmpeg error when running command </usr/bin/ffmpeg -v error -xerror -ss 1862 -i /data/sites/video.wmv -t 0.75 -max_muxing_queue_size 1024 -y -c:v libx264 -pix_fmt yuv420p -profile:v high -level 4.2 -preset slow -crf 21 -threads 4 -vf scale=640:-2 -c:a aac -b:a 128k -strict -2 /generated/tmp/preview007.mp4>: /data/sites/video.wmv: corrupt decoded frame in stream 1\n"

stash_1 | time="2020-06-25T19:29:07Z" level=error msg="ffmpeg error when running command </usr/bin/ffmpeg -v error -xerror -ss 2926 -i /data/sites/video.wmv -t 0.75 -max_muxing_queue_size 1024 -y -c:v libx264 -pix_fmt yuv420p -profile:v high -level 4.2 -preset slow -crf 21 -threads 4 -vf scale=640:-2 -c:a aac -b:a 128k -strict -2 /generated/tmp/preview011.mp4>: /data/sites/video.wmv: corrupt decoded frame in stream 1\n"

stash_1 | time="2020-06-25T19:29:07Z" level=error msg="ffmpeg error when running command </usr/bin/ffmpeg -v error -f concat -i /generated/tmp/files.txt -y -c copy /generated/screenshots/980f24481de546b4e4bec431935b8ba1.mp4>: [mov,mp4,m4a,3gp,3g2,mj2 @ 0x555556a99880] moov atom not found\n[concat @ 0x555556a8e2c0] Impossible to open '/generated/tmp/preview000.mp4'\n/generated/tmp/files.txt: Invalid data found when processing input\n"

time="2020-06-25T19:29:07Z" level=info msg="Generate finished"scene marker 5 of 52> scene marker 1 of 5```

### PR DESCRIPTION
**Pull request by JoeSmithStarkers**
When a preview generation fails (often for wmv/avi files), the new code tries with less stricted (no xerror) and more time consuming options (slow+fast seek). Fixes #635

Fix a minor issue when stash downloads ffmpeg/ffprobe, but doesn't re-detect paths.

Added comment about restoring a backup with a move operation.
Added .DS_Store to ignore list (mac osx annoying file)
Added pkg/pkg to ignore list (can't seem to configure goland to use the vendor dir)

### CODE REVIEW

File: pkg/database/database.go [hunk 1]
```diff
@@ -116,6 +116,7 @@ func Backup(backupPath string) error {
 }
 
 func RestoreFromBackup(backupPath string) error {
+	// TODO: should rename/move the backup, a restore operation should leave the backup intact.
```
Comment (WithoutPants) [inline pkg/database/database.go:119]: This method is used specifically when the migration process fails. We don't want to leave backup files around every time the migration fails. It should probably be documented as such, and future iterations of this method may behave differently if we expose this in the external API, but I don't think this TODO is valid.

File: pkg/ffmpeg/encoder_screenshot.go [hunk 2]
```diff
@@ -21,7 +21,9 @@ func (e *Encoder) Screenshot(probeResult VideoFile, options ScreenshotOptions) e
 		"-v", options.Verbosity,
 		"-ss", fmt.Sprintf("%v", options.Time),
 		"-y",
-		"-i", probeResult.Path, // TODO: Wrap in quotes?
+		// TODO: Wrap in quotes?, not required on linux/darwin. quotes are a shell level argument escape separator.
+		// Don't know about windows.
+		"-i", probeResult.Path,
```
Comment (WithoutPants) [inline pkg/ffmpeg/encoder_screenshot.go:26]: Yeah, pretty sure that TODO is no longer valid. Please remove the TODO altogether.

File: pkg/database/database.go (hunk 1 above)
Comment (JoeSmithStarkers) [reply pkg/database/database.go]: Sorry, i should have checked further. Just instinctual reaction to seeing a backup being moved. I've removed the comment.

File: pkg/ffmpeg/encoder_screenshot.go (hunk 2 above)
Comment (JoeSmithStarkers) [reply pkg/ffmpeg/encoder_screenshot.go]: Done. removed.

File: pkg/ffmpeg/encoder_scene_preview_chunk.go [hunk 3]
```diff
@@ -14,12 +14,43 @@ type ScenePreviewChunkOptions struct {
...
+			slowSeek = fallbackMinSlowSeek
+		} else {
+			slowSeek = fastSeek
+			fastSeek = 0
+		}
+	}
+
+	if fastSeek > 0 {
+		args = append(args, "-ss")
+		args = append(args, strconv.FormatFloat(fastSeek, 'f', 2, 64))
```
Comment (bnkai) [inline pkg/ffmpeg/encoder_scene_preview_chunk.go:42]: shouldn't this be `args = append(args, strconv.FormatFloat(options.StartTime, 'f', 2, 64))` ?

**Comment by bnkai** [comment]
Seems to work ok.
Tried with a couple of avis that where throwing a header missing error.
As  a sidenote setting the start time to say 2% seems to reduce the specific error cases ( i  had that set before the test and the file would generate without error / fallback. Removed that and the fallback method was triggered and worked as intended )

File: pkg/ffmpeg/encoder_scene_preview_chunk.go [hunk 4]
```diff
@@ -14,12 +14,43 @@ type ScenePreviewChunkOptions struct {
...
+		args = append(args, "-xerror")
+	} else {
+		// Fallback try a combination of fast/slow seek instead of only fastseek
+		if fastSeek > fallbackMinSlowSeek {
+			fastSeek = fastSeek - fallbackMinSlowSeek
+			slowSeek = fallbackMinSlowSeek
+		} else {
+			slowSeek = fastSeek
+			fastSeek = 0
+		}
```
Comment (WithoutPants) [inline pkg/ffmpeg/encoder_scene_preview_chunk.go:37]: I think this needs some further documentation. It's not clear to me what it being done here and why. Also need to rationale for the `fallbackMinSlowSeek` value. This seems like it would give some unexpected behaviour if the video file is particularly short.

Comment (JoeSmithStarkers) [reply pkg/ffmpeg/encoder_scene_preview_chunk.go]: I've slightly refactored the code to make it easier to understand, and commented it better.
