### PR TITLE
Bugfix: AVIF Image PHash Support

### LINKED ISSUE #6535: Bug: Image Phashing Doesn't Support AVIF
### Describe the bug

WIth the addition of https://github.com/stashapp/stash/pull/6497 it looks like it has issues phashing AVIF files. This is more than likely due to the upstream issues that we encountered to even partially support importing and generating some content for them.

### Steps to reproduce

Try and generate a Phash for a AVIF Image

### Expected behaviour

Phash the AVIF Image

### Screenshots or additional context

Dogma has volunteered his logs.

### Stash version

Develop

### Device details

_No response_

### Relevant log output

```shell

```

### PR DESCRIPTION
**Pull request by Gykes**
With the addition of https://github.com/stashapp/stash/pull/6497 it allows users to generate PHash for images. AVIF was spitting out errors due to FFMPEG not playing well with stdin and AVIF. This corrects the issue by converting to BMP first so that the image can be hashed. 

fixes: https://github.com/stashapp/stash/issues/6535

### CODE REVIEW

**Comment by Gykes** [comment]
Will be testing with HEIC tomorrow. If not I will make some additions to support.

File: pkg/hash/imagephash/phash.go [hunk 1]
```diff
@@ -27,7 +32,13 @@ func Generate(imageFile *models.ImageFile) (*uint64, error) {
 }
 
 // loadImage loads an image from disk and decodes it.
-func loadImage(imageFile *models.ImageFile) (image.Image, error) {
+// For AVIF files, ffmpeg is used to convert to BMP first since Go has no built-in AVIF decoder.
+func loadImage(encoder *ffmpeg.FFMpeg, imageFile *models.ImageFile) (image.Image, error) {
+	ext := strings.ToLower(filepath.Ext(imageFile.Path))
```
Comment (WithoutPants) [inline pkg/hash/imagephash/phash.go:37]: I believe this will break for images in zip files.

**Review by WithoutPants — CHANGES_REQUESTED** [review]

File: pkg/hash/imagephash/phash.go (hunk 1 above)
Comment (Gykes) [reply pkg/hash/imagephash/phash.go:37]: We check for AVIF in zips at the initial scan and reject them if so. I can add in extra logic incase zips make it through but they shouldn't get this far.

Comment (WithoutPants) [reply pkg/hash/imagephash/phash.go:37]: Yeah an extra sanity check can't hurt.

Comment (Gykes) [reply pkg/hash/imagephash/phash.go:37]: Done
