### PR TITLE
Autotag support for images and galleries

### LINKED ISSUE #977: [Bug Report] Auto-tagging does not import tags from images or galleries
Auto-tagging doesn't import metadata (tags, performers, studios, etc) from image file paths.

### PR DESCRIPTION
**Pull request by WithoutPants**
* Adds compound filters (`AND`, `NOT`, `OR`) for image and gallery queries. Refactored the queryBuilders for these accordingly.
* Adds autotag functionality for images and galleries.

Note that images in zips may not tag correctly when autotagging from performer/studio/tag due to the way that regex interacts with the null character in the image paths. This will be addressed when the character for zip paths is changed at a later date.

Resolves #977

### CODE REVIEW

**Comment by bnkai** [comment]
A join with the images table for the gallery queries seems to have been removed
```
Error executing find query with SQL: SELECT DISTINCT galleries.id FROM galleries GROUP BY galleries.id ORDER BY COUNT(distinct images.id) ASC LIMIT 40 OFFSET 0 , args: [], error: no such column: images.id
```
This makes the AVG Resolution filter and the sort by Images Count to fail in the `Galleries` page.

File: pkg/models/model_image.go [hunk 1]
```diff
@@ -40,6 +41,16 @@ type ImagePartial struct {
 	UpdatedAt   *SQLiteTimestamp     `db:"updated_at" json:"updated_at"`
 }
 
+// GetTitle returns the title of the scene. If the Title field is empty,
```
Comment (bnkai) [inline pkg/models/model_image.go:44]: typo
```suggestion
// GetTitle returns the title of the image. If the Title field is empty,
```
