### PR TITLE
Warn on charset decoding issues

### LINKED ISSUE #3566: [Bug Report] Charencoding issue when scanning a zip gallery
**Describe the bug**
I am getting the following error:

Error scanning zip file "/content/MetArt/2024/test.zip": failed to lookup charset IBM424_ltr, language he

I narrowed down that if the jpg name has '-Ti' in the name then it would throw this error.

Out of the 13 zip files listed below, 5 of them have '-Ti' on the jpg file names.  I haven't figured out the other combinations for the other ones, but I imagine it's the same issue.

DogmaDragon hinted it might have something to do with https://github.com/stashapp/stash/pull/3389 when I inquired in the help channel on Discord.

MetArt_2007-07-16_AMATEURISH-EVI-B-by-JAN-VELS_9d944_high.zip
MetArt_2011-05-12_TIMELESS-NASTYA-J-by-NATASHA-SCHON_74db3_high.zip
MetArt_2012-07-14_ORGANZA-NAOMI-E-by-ANGELA-LININ_42d4f_high.zip
MetArt_2014-04-18_ROVINTH-EMILY-BLOOM-by-GONCHAROV_6162f_high.zip
MetArt_2016-04-30_TIRZA-KALEESY-by-FABRICE_b3155_high.zip
MetArt_2016-05-12_TIPICA-LUCY-LI-by-DELTAGAMMA_fc7fc_high.zip
MetArt_2019-04-15_TIMELESS-OPHELIA-by-MATISS_510cf_high.zip
MetArt_2020-09-29_MY-FANTASIES-TINA-TINY-by-ALEX-LYNN_2fef0_high.zip
MetArt_2020-10-29_OUTDOOR-ROMP-TINA-TINY-by-ALEX-LYNN_6e58e_high.zip
MetArt_2020-12-03_LOLLIPOP-TINA-TINY-by-ALEX-LYNN_61255_high.zip
MetArt_2021-05-02_GIRL-TIME-KERTU-by-KOENART_7cc2b_high.zip
MetArt_2022-08-14_MY-TIME-AWAY-BABY-NICOLS-by-ERRO_69726_high.zip

**To Reproduce**
1. Create a single image (you can have more, but one is fine for testing) and name that image '-Ti.jpg'.
2. Zip it to use as an image gallery, the name of this file doesn't seem to matter.
3. Try to scan to import it into Stash.  You should get the above error.

**Stash Version: (from Settings -> About):**
v0.19.1-73-g88b3b87f

**Additional context**
If you want to use a longer file name, an example would be 'MetArt_My-Time-Away_Baby-Nicols_high_0134.jpg'

### PR DESCRIPTION
**Pull request by WithoutPants**
Fixes #3566 

Instead of throwing an error when we can't detect the encoding, look up the charset, or transform the string, it now logs a warning and leaves the filename(s) unchanged.

In the case of `-Ti.jpg` names, it will warn that the zip charset is `IBM424_ltr (he)`, then warn that the charset was failed to be looked up, but it should otherwise function correctly.

### CODE REVIEW

File: pkg/file/zip.go [hunk 1]
```diff
@@ -58,28 +58,30 @@ func newZipFS(fs FS, path string, info fs.FileInfo) (*ZipFS, error) {
...
-		}
-
-		decoder := e.NewDecoder()
-		for _, f := range zipReader.File {
-			f.Name, _, err = transform.String(decoder, f.Name)
-			if err != nil {
-				reader.Close()
-				return nil, fmt.Errorf("failed to decode %v: %w", []byte(f.Name), err)
+			// if we can't find the encoding, just assume it's UTF8
+			logger.Warnf("Failed to lookup charset %s, language %s", d.Charset, d.Language)
```
Comment (mrnejc) [inline pkg/file/zip.go:72]: it would be useful to add path information to this message / user can then fix the underlying problem instead of application just filling the log ...
